# Generated by Django 2.1.7 on 2019-03-28 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='TicketEnvelope',
            fields=[
                ('sku', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=150, verbose_name='Subject')),
                ('priority', models.PositiveIntegerField(choices=[(4, 'Urgent'), (3, 'High'), (2, 'Medium'), (1, 'Low')], default=1)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Open'), (0, 'Suspended'), (-1, 'Close')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticket.Department', verbose_name='department')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_driver', to=settings.AUTH_USER_MODEL, verbose_name='Driver')),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_passenger', to=settings.AUTH_USER_MODEL, verbose_name='Passenger')),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envelope', to='trip.Trip', verbose_name='trip')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TicketLetter',
            fields=[
                ('sku', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='Message')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticket.TicketEnvelope', verbose_name='reply')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_user', to=settings.AUTH_USER_MODEL, verbose_name='letter user')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created'],
            },
        ),
    ]
