# Generated by Django 2.1.7 on 2019-03-26 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('-created', 'status'), 'verbose_name': 'trip', 'verbose_name_plural': 'trips'},
        ),
        migrations.AddField(
            model_name='trip',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
