# Generated by Django 2.1.7 on 2019-03-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20190326_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='init_price',
            field=models.PositiveIntegerField(null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[(1, 'front seat'), (2, 'left seat'), (3, 'middle seat'), (4, 'right seat')], null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'singular'), (2, 'plural')], null=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='trip.Trip', verbose_name='trip'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='type_price',
            field=models.SmallIntegerField(choices=[(1, 'cash'), (2, 'online')], default=2, null=True),
        ),
    ]
