# Generated by Django 2.1.7 on 2019-03-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_auto_20190326_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('status', '-created'), 'verbose_name': 'trip', 'verbose_name_plural': 'trips'},
        ),
    ]
